import type { Metadata } from "next";
import { site } from "@/lib/site";

/**
 * The site-wide social card image, generated by src/app/opengraph-image.tsx.
 *
 * Next merges a file-convention `opengraph-image` into the segment it sits in,
 * but a page's own metadata *shallow*-merges over the layout's: any page that
 * declares an `openGraph` block replaces the root's wholesale and drops the
 * image along with it. Twitter behaves the same way. So every page builds its
 * card through `socialCard()` rather than hand-rolling the block, which keeps
 * the image attached to all of them and gives one place to change it.
 */
const socialImage = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: `${site.name} — ${site.tagline}`,
} as const;

type SocialCardInput = {
  /** Title for the card. Usually the page title plus the site name. */
  title: string;
  description: string;
  /** Root-relative path, e.g. "/about". Resolved against `metadataBase`. */
  url: string;
};

type ArticleInput = SocialCardInput & {
  publishedTime?: string;
  modifiedTime?: string;
};

/** OG + Twitter for a standard page. */
export function socialCard({
  title,
  description,
  url,
}: SocialCardInput): Pick<Metadata, "openGraph" | "twitter"> {
  return {
    openGraph: {
      type: "website",
      title,
      description,
      url,
      siteName: site.name,
      locale: site.locale,
      images: [socialImage],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [socialImage],
    },
  };
}

/** OG + Twitter for an article, carrying its publication timestamps. */
export function articleCard({
  title,
  description,
  url,
  publishedTime,
  modifiedTime,
}: ArticleInput): Pick<Metadata, "openGraph" | "twitter"> {
  return {
    openGraph: {
      type: "article",
      title,
      description,
      url,
      siteName: site.name,
      locale: site.locale,
      images: [socialImage],
      ...(publishedTime ? { publishedTime } : {}),
      ...(modifiedTime ? { modifiedTime } : {}),
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [socialImage],
    },
  };
}
